export const PROACTIVE_LOOP_TICK_MS = 15_000;
export const PROACTIVE_PRUNE_TICK_MS = 60_000;
export const PROACTIVE_RECENT_ADVICE_COOLDOWN_FACTOR = 0.55;
export const PROACTIVE_MIN_RECENT_ADVICE_COOLDOWN_MS = 90_000;

export const AUTO_VISION_MIN_DELAY_MS = 8 * 60_000;
export const AUTO_VISION_JITTER_MS = 12 * 60_000;

export const PROACTIVE_IMMERSED_COMPANION_SESSION_MIN_MS = 15 * 60_000;
export const PROACTIVE_IMMERSED_COMPANION_SILENCE_MIN_MS = 12 * 60_000;

export const PROACTIVE_MAX_MEMORY_CALLBACK_PROBABILITY = 0.72;
export const PROACTIVE_MAX_UNFINISHED_THREAD_PROBABILITY = 0.35;
export const PROACTIVE_BASE_UNFINISHED_THREAD_PROBABILITY = 0.1;
export const PROACTIVE_ADVICE_STREAK_MEMORY_BOOST = {
  one: 0.12,
  many: 0.22,
};
export const PROACTIVE_ADVICE_STREAK_THREAD_BOOST = {
  one: 0.08,
  many: 0.18,
};
